spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: duydat
    password: dat123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: "thisIsASecretKeyForJWTThatIsVeryLongAndSafe"
    expirationMs: 86400000 # 24h

logging:
  level:
    org.springframework.security: DEBUG


server:
  port: 8060

