
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: duydat
    password: dat123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: "thisIsASecretKeyForJWTThatIsVeryLongAndSafe"
    expirationMs: 86400000


server:
  port: 8073
